apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      # initContainers:
      # - name: wait-for-sqlserver
      #   image: busybox:1.28
      #   command: ['sh', '-c', 'until nc -z sqlserver 1433; do echo waiting for sqlserver; sleep 2; done;']
      containers:
      - name: webapi
        image: goncalvesc97/fiap-tc-4-login-ms:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # Configuração do ambiente de banco de dados 
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: login-ms-secret
              key: DB_CONNECTION_STRING
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: login-ms-secret
              key: DB_NAME

        # Configuração da chave de autenticação da API
        - name: API_AUTHENTICATION_KEY
          valueFrom:
            secretKeyRef:
              name: login-ms-secret
              key: API_AUTH_TOKEN